name: nc-py37-geopandas
channels:
  - conda-forge
dependencies:
  - appnope=0.1.0=py37_1000
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - basemap=1.2.0=py37hd103db2_4
  - bleach=3.1.0=py_0
  - boost-cpp=1.68.0=h6f8c590_1000
  - bzip2=1.0.8=h01d97ff_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37hccf1714_0
  - cfitsio=3.470=h389770f_1
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cryptography=2.7=py37h212c5bf_0
  - curl=7.65.3=h22ea746_0
  - cycler=0.10.0=py_1
  - dash=1.0.2=py_0
  - dash-core-components=1.0.0=py_0
  - dash-daq=0.1.7=py_0
  - dash-html-components=1.0.0=py_0
  - dash-renderer=1.0.0=py_0
  - dash-table=4.0.2=py_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - descartes=1.1.0=py_3
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=h6de7cb9_1003
  - fiona=1.8.6=py37h7eb7563_3
  - flask=1.1.1=py_0
  - flask-compress=1.4.0=py_0
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.10.0=h24853df_0
  - freexl=1.0.5=h1de35cc_1002
  - gdal=2.4.1=py37h39889d8_9
  - geopandas=0.5.1=py_0
  - geos=3.7.2=h6de7cb9_1
  - geotiff=1.4.3=h113155d_1001
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.1.7=h01d97ff_1
  - glib=2.58.3=h9d45998_1002
  - hdf4=4.2.13=hf3c6af0_1002
  - hdf5=1.10.5=nompi_h0cbb7df_1100
  - icu=58.2=h0a44026_1000
  - idna=2.8=py37_1000
  - ipykernel=5.1.1=py37h5ca1d4c_0
  - ipython=7.6.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.0=py_0
  - itsdangerous=1.1.0=py_0
  - jedi=0.14.1=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h1de35cc_1001
  - json-c=0.13.1=h1de35cc_1001
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.10=h6659575_1005
  - kiwisolver=1.1.0=py37h770b8ee_0
  - krb5=1.16.3=hcfa6398_1001
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=8.0.0=4
  - libcxxabi=8.0.0=4
  - libdap4=3.20.2=hae55d67_1000
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgdal=2.4.1=h667f07c_9
  - libgfortran=3.0.1=0
  - libiconv=1.15=h01d97ff_1005
  - libkml=1.3.0=h71ee1b2_1009
  - liblapack=3.8.0=10_openblas
  - libnetcdf=4.6.2=h1a02027_1002
  - libopenblas=0.3.6=hd44dcd8_4
  - libpng=1.6.37=h2573ce8_0
  - libpq=11.4=h756f0eb_3
  - libsodium=1.0.17=h01d97ff_0
  - libspatialindex=1.9.0=h6de7cb9_1
  - libspatialite=4.3.0a=hb3e03d6_1030
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.0.10=hd08fb8f_1003
  - libxml2=2.9.9=hd80cff7_2
  - llvm-openmp=8.0.0=h770b8ee_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37_0
  - matplotlib-base=3.1.1=py37h3a684a6_0
  - mistune=0.8.4=py37h1de35cc_1000
  - munch=2.3.2=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - notebook=6.0.0=py37_0
  - numpy=1.16.4=py37h6b0580a_0
  - openblas=0.3.6=hd44dcd8_4
  - openjpeg=2.3.1=hc1feee7_0
  - openssl=1.1.1c=h01d97ff_0
  - palettable=3.2.0=py_0
  - pandas=0.25.0=py37h86efe34_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=h0a44026_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h01d97ff_1003
  - plotly=4.0.0=py_0
  - poppler=0.67.0=hd5eb092_7
  - poppler-data=0.4.9=1
  - postgresql=11.4=h25afefd_3
  - proj4=5.2.0=h6de7cb9_1004
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.1=py_0
  - pyproj=1.9.6=py37h01d97ff_1002
  - pyqt=5.9.2=py37h2a560b1_0
  - pyrsistent=0.15.3=py37h01d97ff_0
  - pysal=2.0.0=py_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py37h01d97ff_0
  - pyzmq=18.0.2=py37hee98d25_2
  - qt=5.9.7=h93ee506_2
  - qtconsole=4.5.1=py_0
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py37_1
  - retrying=1.3.3=py_2
  - rtree=0.8.3=py37h666c49c_1002
  - scikit-learn=0.21.3=py37hd4ffd6c_0
  - scipy=1.3.0=py37hab3da7d_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h0567c5e_1006
  - sip=4.19.8=py37h0a44026_1000
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=hb7d70f7_0
  - statsmodels=0.10.1=py37heacc8b8_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.3=py37h01d97ff_0
  - traitlets=4.3.2=py37_1000
  - tzcode=2019a=h01d97ff_1002
  - urllib3=1.25.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.15.5=py_0
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.5.0=py37_0
  - xerces-c=3.2.2=h4db8090_1003
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zlib=1.2.11=h01d97ff_1005
  - zstd=1.4.0=ha9f0a20_0

